export const FETCH_API_PRODUCTS = "FETCH_API_PRODUCTS";
export const FETCH_API_PRODUCTS_SUCCESS = "FETCH_API_PRODUCTS_SUCCESS";
export const FETCH_API_PRODUCTS_ERR = "FETCH_API_PRODUCTS_ERR";

export const FETCH_API_DISPCOVER = "FETCH_API_DISPCOVER";
export const FETCH_API_DISPCOVER_SUCCESS = "FETCH_API_DISPCOVER_SUCCESS";
export const FETCH_API_DISPCOVER_ERR = "FETCH_API_DISPCOVER_ERR";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERR = "ADD_TO_CART_ERR";

export const UPDATE_TO_CART = "UPDATE_TO_CART";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
